affinity: {}
configuration: ""
existingConfigMap: ""
existingSecret: actual-up
fullnameOverride: ""
imagePullSecrets: []
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
replicaCount: 1
terminationGracePeriodSeconds: 60
tolerations: []
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/maxexcloo/actual-up
  tag: ""
ingress:
  annotations: {}
  className: ""
  enabled: false
  host: actual-up.example.com
  path: /webhooks/up
  tls: []
networkPolicy:
  enabled: false
  ingressFrom: []
persistence:
  existingClaim: ""
  size: 1Gi
  storageClass: ""
podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
  runAsNonRoot: true
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 25m
    memory: 128Mi
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsGroup: 1000
  runAsUser: 1000
  capabilities:
    drop:
      - ALL
service:
  port: 3000
  type: ClusterIP
serviceMonitor:
  additionalLabels: {}
  enabled: false
  interval: 30s
