{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "actual-up.fullname" . }}
  labels:
    {{- include "actual-up.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "actual-up.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
      port: http
{{- end }}
